name: oxf_client
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.4.2
  path_provider: ^2.1.2
  intl: ^0.19.0
  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.8
  path: ^1.9.1
  mask_text_input_formatter: ^2.7.0
  flutter_masked_text2: ^0.9.1
  dropdown_search: ^5.0.6
  http: ^0.13.6

  webview_flutter: ^4.7.0
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/background.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/oxf_client.png"
